# Store all sensitive values here.
# In production replace with sealed-secrets / external-secrets-operator.
apiVersion: v1
kind: Secret
metadata:
  name: openseedr-secrets
  namespace: openseedr
type: Opaque
stringData:
  DB_PASSWORD: "changeme"
  JWT_SECRET: "changeme-at-least-32-chars-long!!"
  QBT_PASS: "changeme"
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  GITHUB_CLIENT_ID: ""
  GITHUB_CLIENT_SECRET: ""
  GRAFANA_PASSWORD: "changeme"
